post page added with functionality of adding a new post and delete an…
SibghatUllah-Devsinc/Project-2 pull request #1
Opened 2023-01-04 15:00 UTC by SibghatUllah-Devsinc

… existing post

2023-01-04 15:58 UTC, zakria-devsinc requested changes

2023-01-04 15:58 UTC, zakria-devsinc commented on src/api/index.js
> +
commented code

2023-01-04 15:58 UTC, zakria-devsinc commented on src/api/posts.js
> +// const deletePost = (id) => axios.delete('URL')
commented code

2023-01-04 15:58 UTC, zakria-devsinc commented on src/components/Comments/CommentsList.js
> +//     else{
commented code

2023-01-04 15:58 UTC, zakria-devsinc commented on src/components/Comments/CommentsList.js
> +//     </ul>
commented code

2023-01-04 15:58 UTC, zakria-devsinc commented on src/components/MainHeader/Navigation.jsx
> +        {ctx.isLoggedIn && (
optimize code

2023-01-04 15:58 UTC, zakria-devsinc commented on src/components/Post/Delete.jsx
> +
white spaces

2023-01-04 15:58 UTC, zakria-devsinc commented on src/components/Post/Delete.jsx
> +  // const userPosts = props.userPost.filter((post)=> post.id !== props.id)
cmmented code

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Login/Login.jsx
>        history.push("/");
useRouter use karo

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AddPost.js
> +      console.log("added")
remove consoles

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AddPost.js
> +      var existingPosts = JSON.parse(localStorage.getItem('posts'));
use const

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AllPosts.js
> +
spaces

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AllPosts.js
> +
space

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AllPosts.js
> +
space

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AllPosts.js
> +const [localpost , setLocalPost] = useState()
handler or state ka darmyan space enter kia karo

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AllPosts.js
> +    var localPosts = JSON.parse(localStorage.getItem('posts'));
yar ye var khatam karo saray

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/AllPosts.js
> +    console.log(localPosts);
consoles b saray remove karo

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/DeletePost.js
> +  console.log(ctx.userId);
console

2023-01-04 15:58 UTC, zakria-devsinc commented on src/utils/utils.js
> +// }
remove comments

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/PostList.js
> + var posts = props.allPosts
use const

2023-01-04 15:58 UTC, zakria-devsinc commented on src/components/Post/NoPostsFound.js
> +const NoPostsFound = () => {
line break

2023-01-04 15:58 UTC, zakria-devsinc commented on src/container/Posts/PostForm.js
> +    console.log(localPosts.length)
consoles

2023-01-05 13:25 UTC, SibghatUllah-Devsinc commented
updation done

On Wed, Jan 4, 2023 at 8:58 PM Muhammad Zakria ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/api/index.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061574278>
> :
>
> > @@ -0,0 +1,7 @@
> +// import axios from 'axios';
> +
> +// let instance = axios.config({
> +//   URl: 'API'
> +// })
> +
>
> commented code
> ------------------------------
>
> In src/api/posts.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061574954>
> :
>
> > +
> +// const addPost = (post) => axios.post('URL',post)
> +
> +// const updatePost = (post) => axios.put('URL',post)
> +
> +// const deletePost = (id) => axios.delete('URL')
>
> commented code
> ------------------------------
>
> In src/components/Comments/CommentsList.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061575308>
> :
>
> > +// import CommentItem from './CommentItem';
> +// import classes from './CommentsList.module.css';
> +
> +// const CommentsList = (props) => {
> +//     const getPosts= async() =>{
> +//   const response = await fetch('https://jsonplaceholder.typicode.com/posts');
> +//   if (!response.ok) {
> +//     throw new Error('Something went wrong! '+ response.status);
> +//   }
> +
> +//   var data =await  response.json();
> +//   if(localStorage.getItem("posts") == null){
> +//     localStorage.setItem("posts", JSON.stringify(data));
> +//     var localPosts = JSON.parse(localStorage.getItem('posts'));
> +//     setLocalPost(localPosts)
> +//     console.log(localPosts);
> +//     }
> +//     else{
>
> commented code
> ------------------------------
>
> In src/components/Comments/CommentsList.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061586135>
> :
>
> > +// }
> +// getPosts().catch(error =>{
> +//   setError(error.message)
> +// });
> +// } ,[])
> +//   return (
> +//     <ul className={classes.comments}>
> +//       {props.comments.map((comment) => (
> +//         <CommentItem key={comment.id} text={comment.comment} />
> +//       ))}
> +//     </ul>
>
> commented code
> ------------------------------
>
> In src/components/MainHeader/Navigation.jsx
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061587835>
> :
>
> > +      {ctx.isLoggedIn && (
> +          <li>
> +          <NavLink to="/home" activeClassName={classes.active}>Home</NavLink>
> +          </li>
> +        )}
> +        {ctx.isLoggedIn && (
> +          <li>
> +          <NavLink to="/addPost" activeClassName={classes.active}>Add New Post</NavLink>
> +          </li>
> +        )}
> +        {ctx.isLoggedIn && (
> +          <li>
> +          <NavLink to="/deletePost" activeClassName={classes.active}>Delete Post Post</NavLink>
> +          </li>
> +        )}
> +        {ctx.isLoggedIn && (
>
> optimize code
> ------------------------------
>
> In src/components/Post/Delete.jsx
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061588617>
> :
>
> > +
> +
> +
> +
>
> white spaces
> ------------------------------
>
> In src/components/Post/Delete.jsx
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061589016>
> :
>
> > @@ -0,0 +1,26 @@
> +import classes from './PostItem.module.css';
> +
> +
> +
> +
> +const DeleteItem = (props) => {
> +const DeletePost = ()=>{
> +  // const userPosts = props.userPost.filter((post)=> post.id !== props.id)
>
> cmmented code
> ------------------------------
>
> In src/container/Login/Login.jsx
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061627581>
> :
>
> >        existingUser.push({
>          name:formState.nameValue,
>          email:formState.emailValue,
> -        password:formState.passwordValue
> +        password:formState.passwordValue,
> +        userId:"a"+ userId
>        });
>        localStorage.setItem('user', JSON.stringify(existingUser))
>        history.push("/");
>
> useRouter use karo
> ------------------------------
>
> In src/container/Posts/AddPost.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061628085>
> :
>
> > @@ -0,0 +1,17 @@
> +import PostForm from "./PostForm"
> +import {useHistory} from "react-router-dom"
> +
> +function AddPost(){
> +    const history = useHistory()
> +    function addPost(post){
> +      var existingPosts = JSON.parse(localStorage.getItem('posts'));
> +      existingPosts.push(post);
> +      localStorage.setItem('posts', JSON.stringify(existingPosts))
> +      history.push("/home");
> +      console.log("added")
>
> remove consoles
> ------------------------------
>
> In src/container/Posts/AddPost.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061628350>
> :
>
> > @@ -0,0 +1,17 @@
> +import PostForm from "./PostForm"
> +import {useHistory} from "react-router-dom"
> +
> +function AddPost(){
> +    const history = useHistory()
> +    function addPost(post){
> +      var existingPosts = JSON.parse(localStorage.getItem('posts'));
>
> use const
> ------------------------------
>
> In src/container/Posts/AllPosts.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061628669>
> :
>
> > +
> +
>
> spaces
> ------------------------------
>
> In src/container/Posts/AllPosts.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061628879>
> :
>
> > @@ -0,0 +1,44 @@
> +import { useEffect, useState } from "react";
> +import NoPostsFound from "../../components/Post/NoPostsFound";
> +import PostList from "./PostList"
> +
> +
> +function AllPosts(){
> +
>
> space
> ------------------------------
>
> In src/container/Posts/AllPosts.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061629037>
> :
>
> > @@ -0,0 +1,44 @@
> +import { useEffect, useState } from "react";
> +import NoPostsFound from "../../components/Post/NoPostsFound";
> +import PostList from "./PostList"
> +
> +
> +function AllPosts(){
> +
> +const [error , setError] = useState()
> +const [localpost , setLocalPost] = useState()
> +  useEffect( ()=>{
> +
>
> space
> ------------------------------
>
> In src/container/Posts/AllPosts.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061629568>
> :
>
> > @@ -0,0 +1,44 @@
> +import { useEffect, useState } from "react";
> +import NoPostsFound from "../../components/Post/NoPostsFound";
> +import PostList from "./PostList"
> +
> +
> +function AllPosts(){
> +
> +const [error , setError] = useState()
> +const [localpost , setLocalPost] = useState()
>
> handler or state ka darmyan space enter kia karo
> ------------------------------
>
> In src/container/Posts/AllPosts.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061630130>
> :
>
> > +function AllPosts(){
> +
> +const [error , setError] = useState()
> +const [localpost , setLocalPost] = useState()
> +  useEffect( ()=>{
> +
> +  const getPosts= async() =>{
> +  const response = await fetch('https://jsonplaceholder.typicode.com/posts');
> +  if (!response.ok) {
> +    throw new Error('Something went wrong! '+ response.status);
> +  }
> +
> +  const data =await  response.json();
> +  if(localStorage.getItem("posts") == null){
> +    localStorage.setItem("posts", JSON.stringify(data));
> +    var localPosts = JSON.parse(localStorage.getItem('posts'));
>
> yar ye var khatam karo saray
> ------------------------------
>
> In src/container/Posts/AllPosts.js
> <https://github.com/SibghatUllah-Devsinc/Project-2/pull/1#discussion_r1061630372>
> :
>
> > +const [error , setError] = useState()
> +const [localpost , setLocalPost] = useState()
> +  useEffect( ()=>{
> +
> +  const getPosts= async() =>{
> +  const response = await fetch('https://jsonplaceholder.typicode.com/posts');
> +  if (!response.ok) {
> +    throw new Error('Something went wrong! '+ response.status);
> +  }
> +
> +  const data =await  response.json();
> +  if(localStorage.ge [...]

2023-01-05 13:30 UTC, merged